#!/bin/zsh
# Merchant point v2: a military shop — open stalls folding out of the side wall of an army box truck, «SHOP» sign.
cd "${0:A:h}/../.."
A=art_requests/merchant_point_v2
higgsfield generate create gpt_image_2_5 --quality high --resolution 2k --aspect_ratio 1:1 \
  --image-references art_requests/route_points_v1/services.png --image-references art_requests/merchant_point_v1/review/03_forms_c/material_ref.png \
  --prompt "Concept sheet with FOUR variants to choose from, exact grid 2 columns x 2 rows, four equal square cells with a thin gap. Each cell is one route-map point: a small round low-poly diorama tile (same footprint and size in every cell) seen from the same high three-quarter top-down camera as the first reference image, on a plain soft neutral background, in the same simple minimalist game style: chunky slightly cartoonish low-poly shapes, cute squat proportions, soft rounded bevels, soft pastel military palette (sage and olive green, cream, sand, soft orange accents), soft daylight from upper-left. Small metal parts polished with soft reflections (roughness about 0.2). THE SUBJECT: a MILITARY SHOP — an olive army box truck / van whose whole side wall folds open into a market: hinged side panels swing down into open counters and an awning folds up, shelves and crates of goods spill out (ammo boxes, helmets, grenades on a rack, jerrycans, crates, a weapon rack), all as a cozy rummage stall. Above it a simple sign with the single word SHOP in bold block letters (the only text allowed). Four clearly different variants: 1 top-left: a 6-wheel olive cargo truck with the side flipped down into a long counter and a striped orange-cream awning on poles, crates stacked beside; 2 top-right: a short boxy military van with gull-wing side flaps opening up and down, a counter of goods, a lantern and a SHOP sign on the roof; 3 bottom-left: a truck with a canvas tarp rolled up on one side revealing tiered shelves of gear, a small folding table and a jerrycan pile in front, SHOP sign on a pole; 4 bottom-right: a trailer box behind a small army truck, its side opens into a bright market with a camouflage net canopy, crates and barrels around, glowing SHOP sign board. No other text, no letters except SHOP, no characters." \
  --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1 > $A/url.txt
U=$(cat $A/url.txt); [ -n "$U" ] && curl -sSL -o $A/variants.png "$U" && echo OK; rm -f $A/url.txt
