#!/bin/zsh
# T-130: hub empty building slots as mini construction sites + friendlier locks. Reference sheets for 3D models.
cd "${0:A:h}/../.."
O=art_requests/hub_construction_v1
R=art_requests/reference_shots_v1/01_hub_day.png
STYLE="Exactly the game's minimalist low-poly 3D style from the reference image: chunky simple shapes, soft pastel palette (sage green, cream, warm sand, soft orange accents), flat clean materials with gentle soft shading, the same soft daylight from upper-left as the hub, the same high three-quarter top-down camera as the hub. Small polished metal details (pipes, mixer drum, padlock) with soft rounded bevels and gentle reflections. No text, no letters, no numbers, transparent background, no ground plane beyond each object's own footprint."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 4k --background transparent --image-references $R "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }
gen $O/sites.png --aspect_ratio 3:2 --prompt "Sheet of 3 complete mini construction-site building slots for a hangar hub, exact grid 3 columns x 1 row, each a square plot of the same size, each centered with wide transparent gaps. Each plot: a flat sandy-concrete square pad, fenced by a low striped orange-and-cream barrier fence or barrier tape on short posts, with a few construction props arranged neatly inside and a small sign post with a padlock emblem at the front. 1 small plot: pad, tape on posts, a stack of three pipes, a sign with a lock. 2 medium plot: pad, low fence, a pile of bricks, a stack of planks, a small sand pile, a sign with a lock. 3 large plot: pad, low fence, a small concrete mixer, pipes, bricks, planks, sand, a sign with a lock. $STYLE" &
gen $O/parts.png --aspect_ratio 3:2 --prompt "Sheet of 9 separate construction props for building them as 3D models, exact grid 3 columns x 3 rows, each prop centered in its own equal cell with wide transparent gaps, all at the same scale. Row 1: 1 a stack of three polished steel pipes; 2 a neat pile of bricks; 3 a stack of wooden planks. Row 2: 4 a small sand pile with a shovel stuck in it; 5 a small concrete mixer with a polished drum; 6 a short section of striped orange-and-cream barrier fence. Row 3: 7 two short posts with barrier tape between them; 8 a small sign post with a padlock emblem on its plate; 9 a flat square concrete pad tile with a sandy edge. $STYLE" &
gen $O/locks.png --aspect_ratio 4:3 --prompt "Sheet of 4 friendly, appealing lock variants for locked building slots, exact grid 2 columns x 2 rows, each centered in its own equal cell with wide transparent gaps, same scale. Chunky, cute, rounded and friendly, not menacing. 1 a rounded padlock with a cat-paw emblem on the body, polished brass shackle; 2 a padlock hanging on a short loop of chunky chain links, soft orange enamel body; 3 a padlock with a small key in the keyhole and a little paper tag; 4 a chain wrapped in an X shape with a small padlock in the middle, as if across a gate. $STYLE" &
wait
