#!/bin/zsh
# Backpack items: an ammo series (box + standing cartridge) and a blueprint series (same clipboard, category silhouette).
cd "${0:A:h}/../.."
O=art_requests/icon_kit_v1/sheets
STYLE="Same chunky toy-like 3D style as the first reference image, tactile and pleasant, like a collectible you want to pick up. MATERIALS: polished shiny metal with soft rounded bevels on every edge, glossy low-roughness reflections (roughness about 0.2), crisp soft specular highlights; cardboard and paper matte. Warm key light from upper-left. No text, no letters, no numbers, transparent background, no plates or frames behind the objects."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 4k --background transparent --image-references $O/abilities_v2.png --image-references $O/upgrades_a_v2.png "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }
gen $O/ammo_v2.png --aspect_ratio 16:9 --prompt "A matching SERIES of 8 ammunition item icons for a game backpack. Exact grid 4 columns x 2 rows, each item centered in its own equal cell with wide transparent gaps. EVERY cell uses EXACTLY the same composition, the same three-quarter camera angle from slightly above, the same size and position: a small rectangular ammo box standing on the left with its lid slightly open showing cartridge tips, and ONE big cartridge standing upright to its right, slightly overlapping the box front. The front of each box carries one bold printed emblem of its effect; the standing cartridge's tip and material show the same effect. The series escalates in coolness from plain to ultra. Row 1: 1 STANDARD: plain brown cardboard box with a simple olive stripe, plain brass cartridge with copper tip; 2 INCENDIARY: olive steel tin box with an orange flame emblem, cartridge with a glowing red-orange tip and tiny flames; 3 STUN: olive steel tin with a yellow dizzy spiral and stars emblem, cartridge with a yellow banded tip and little stars; 4 EMP: steel tin with a cyan lightning bolt emblem, cartridge with a crackling electric blue tip. Row 2: 5 EXPLOSIVE: red enamel tin with a black explosion burst emblem, cartridge with a red tip and glowing hot seam; 6 ARMOR-PIERCING: polished gunmetal tin with a silver arrowhead emblem, cartridge with a sharp polished steel penetrator tip; 7 RICOCHET: polished violet-anodized tin with a zigzag bounce arrow emblem, cartridge with a violet tip and a small glowing zigzag trail; 8 CRYO: frosted pale-blue chrome tin with a snowflake emblem and frost on the edges, cartridge with an icy crystal tip and cold mist. $STYLE" &
gen $O/blueprints_v2.png --aspect_ratio 3:2 --prompt "A matching SERIES of 6 blueprint item icons for a game backpack. Exact grid 3 columns x 2 rows, each item centered in its own equal cell with wide transparent gaps. EVERY cell uses EXACTLY the same object, angle, size and position: a wooden clipboard with a polished steel clip at the top, slightly tilted, holding a deep blue blueprint sheet with a faint grid and a corner curl. Only the bold white technical line drawing in the middle of the blue sheet differs, a simple clear silhouette readable at 32 pixels: 1 an assault rifle side view pointing RIGHT (weapon blueprint); 2 a tank side view facing RIGHT (vehicle blueprint); 3 a bunker with a radio antenna (headquarters technology blueprint); 4 a hand grenade (ability blueprint); 5 a supply crate with a star (field bonus blueprint); 6 a small workshop building with a gear (base building blueprint). $STYLE" &
wait
