#!/bin/zsh
# Icon kit, full set after the approved pilot (guides/03_release/07_icon_kit_brief.md).
# Bases come in two separate layers: FACE (inner field, no rim) and RIM (hollow frame).
# Run from the repo root. Each sheet costs 1.25 (medium) or 2.75 (high) credits at 4K.
cd "${0:A:h}/../.."
O=art_requests/icon_kit_v1/sheets
G=assets/illustrations/gpt_image_2_5/icons
P=art_requests/icon_kit_v1/sheets/kit_upgrade_v1.png
STYLE="Style: soft chunky toy-like 3D render like the reference images, rounded big forms, matte materials, warm key light from upper-left, no outlines. No text, no letters, no numbers, transparent background. Every item centered in its own equal grid cell with wide transparent gaps, nothing touching. Anything with a direction points to the RIGHT."
SYM="Objects only: no plates, no frames, no circles or shields behind them, no background. Each symbol filling about 70% of its cell, all at the same scale, simple bold silhouettes readable at 32 pixels."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.(png|jpg|webp)' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }

gen $O/kit_bases_a_v1.png --quality high --resolution 4k --aspect_ratio 1:1 --background transparent --image-references $P --image-references $G/abilities/grenade.png --prompt "Layer kit of icon BASES for a game UI, exact grid 4 columns x 4 rows. Every base comes as a PAIR in two neighbouring cells drawn at EXACTLY the same size and position: first the FACE (only the flat inner enamel field, no rim, no border, no symbol), then the RIM (only the raised outer frame of that same shape, completely hollow and transparent inside, matching the face outline exactly so the rim sits perfectly over the face). Row 1: 1 face of a regular octagon button, teal steel enamel; 2 rim of that octagon, gunmetal with four small screws; 3 face of a square armor plate with cut corners, steel blue; 4 rim of that plate, riveted gunmetal. Row 2: 5 face of a round gear disk, graphite with diagonal yellow-black hazard stripes; 6 rim of that gear: a hollow ring of chunky gear teeth, dark iron; 7 face of an arched wooden signboard, warm honey wood planks; 8 rim of that signboard: a thicker dark wood frame with two nail heads and a small rope loop on top. Row 3: 9 face of a small circle, dark charcoal olive; 10 rim of that circle, bright green bevelled ring; 11 rim of that same circle, red bevelled ring; 12 rim of an army dog tag (rounded rectangle with a hole and a short ball chain at the top), brushed steel, hollow inside. Row 4: 13 face of that dog tag, coral red enamel; 14 face of that dog tag, brass yellow; 15 face of that dog tag, leaf green; 16 face of that dog tag, teal turquoise. $STYLE" &

gen $O/kit_bases_b_v1.png --quality high --resolution 4k --aspect_ratio 4:3 --background transparent --image-references $P --image-references $G/pickups/heart.png --prompt "Layer kit of icon BASES for a game UI, exact grid 4 columns x 3 rows, all items drawn at EXACTLY the same size and position in their cells so layers stack perfectly. FACE = only the flat inner enamel field, no rim, no symbol. RIM = only the raised outer frame, hollow and transparent inside. Row 1: 1 face of an army dog tag (rounded rectangle, hole at top), khaki tan; 2 rim of a heraldic shield (rounded top corners, pointed bottom) in aged bronze with four small rivets, hollow; 3 face of that same heraldic shield, plain neutral grey enamel; 4 rim of a map-pin drop marker (round top, pointed bottom tip), white-cream glossy plastic ring, hollow. Row 2: 5 face of that map pin, cherry red; 6 face of that map pin, warm orange; 7 face of that map pin, sky blue; 8 face of that map pin, olive green. Row 3: 9 face of that map pin, icy light cyan; 10 face of that map pin, teal; 11 soft warm white sunburst aura rays around an empty center; 12 a soft round glow ring, white, subtle. $STYLE" &

gen $O/symbols_2_v1.png --quality medium --resolution 4k --aspect_ratio 5:4 --background transparent --image-references $O/symbols_1_v1.png --prompt "Sprite sheet of 20 icon SYMBOLS, exact grid 5 columns x 4 rows, same style and scale as the reference sheet. Row 1: 1 a rifle magazine with speed lines; 2 a rifle scope with a small gold star; 3 a car steering wheel with a bullet; 4 a bullet hitting a rocket in mid-air with a small spark, both flying right; 5 a bubble spirit level fixed on a short gun barrel. Row 2: 6 an hourglass with a bullet beside it; 7 a torn battle flag still standing on its pole; 8 a crackling electric arc between two tiny cars; 9 an electric plug with a short-circuit spark; 10 a red first-aid kit. Row 3: 11 a curved wall of sandbags; 12 a bullet with a long dotted arc trajectory to a small target, going right; 13 a dashed ghostly outline of a cat soldier; 14 a parachute carrying a supply crate; 15 an open car door with a dash arrow to the right. Row 4: 16 a bulging loot sack; 17 a small steel safe; 18 a wrench with a bright repair spark; 19 a grappling hook with rope; 20 an olive hand grenade with a circular clockwise arrow around it. $SYM $STYLE" &

gen $O/symbols_3_v1.png --quality medium --resolution 4k --aspect_ratio 5:4 --background transparent --image-references $O/symbols_1_v1.png --image-references $G/abilities/airstrike.png --prompt "Sprite sheet of 20 icon SYMBOLS, exact grid 5 columns x 4 rows, same style and scale as the first reference sheet. Row 1: 1 a small propeller plane dropping two bombs, flying right; 2 a quadcopter drone; 3 a czech anti-tank hedgehog of three crossed steel beams; 4 a camouflage hood with its edge fading into transparency; 5 a white cat helmet with ears and a green plus sign. Row 2: 6 a red dynamite stick with a lit fuse; 7 a soft green cloud with a catnip leaf; 8 an olive hand grenade; 9 a small turret shooting a red laser beam to the right; 10 a round land mine. Row 3: 11 a riot shield with a paw print; 12 a big snowflake; 13 a big gold star; 14 a small machine gun turret on a tripod facing right; 15 a small olive jeep facing right. Row 4: 16 a wrench crossed over a wheel; 17 a stack of red bricks; 18 a little bunker with a wrench; 19 a shiny metal alloy ingot; 20 a rolled blue blueprint. $SYM $STYLE" &

gen $O/symbols_4_v1.png --quality medium --resolution 4k --aspect_ratio 5:4 --background transparent --image-references $O/symbols_1_v1.png --prompt "Sprite sheet of 20 icon SYMBOLS, exact grid 5 columns x 4 rows, same style and scale as the reference sheet. Row 1: 1 a field medical tent with a red cross; 2 two riveted armor panels; 3 a robotic arm holding a wrench; 4 a supply crate with a parachute strap; 5 an interceptor missile flying up-right. Row 2: 6 a tesla coil with small lightning; 7 a ring-shaped pulse wave with a cross in the middle; 8 a translucent protective dome; 9 a dish antenna emitting waves; 10 a thick armor plate with bolts. Row 3: 11 a short cannon barrel with a muzzle flash to the right; 12 a coiled ammo belt; 13 a folder of documents with a red seal; 14 a recipe card with a small gear; 15 a gold trophy cup. Row 4: 16 a stopwatch; 17 two crossed rifles; 18 a cat helmet glowing with a white shield aura; 19 a short trench with sandbags; 20 a brass coin token with a paw print. $SYM $STYLE" &

gen $O/symbols_5_v1.png --quality medium --resolution 4k --aspect_ratio 4:3 --background transparent --image-references $O/symbols_1_v1.png --image-references assets/ui/buildings/merchant.png --prompt "Sprite sheet of 12 simple SYMBOLS for hub workbenches, exact grid 4 columns x 3 rows, same style and scale as the first reference. Single simple objects, not buildings in scenes. Row 1: 1 a small 3D printer with a cat helmet inside; 2 a monitor showing a map; 3 a little car under a canopy roof, facing right; 4 a bunker with an antenna. Row 2: 5 a red toolbox with a wrench; 6 a market stall with a striped awning; 7 a target board on sandbags; 8 a press machine with a gear. Row 3: 9 a cork board with pinned flags; 10 a locker with a hanging uniform; 11 a rack with two rifles; 12 three traffic cones. $SYM $STYLE" &
wait
