#!/bin/zsh
# Stage 3 of the shiny-metal pass: HQ, garage, field bonuses, resources, hub workbenches. 3 sheets x 12 (4 x 3).
cd "${0:A:h}/../.."
O=art_requests/icon_kit_v1/sheets
STYLE="Same chunky toy-like 3D style as the first reference image. One bold simple object per cell with a unique, instantly readable silhouette at 32 pixels; no plates, no frames, no circles or shapes behind, no background. MATERIALS: wherever there is metal, make it polished shiny metal with soft rounded bevels on every edge and glossy low-roughness reflections (roughness about 0.2), crisp soft specular highlights; painted parts are glossy enamel; fabric, wood and paper stay matte. Warm key light from upper-left. No text, no letters, no numbers, transparent background. Anything with a direction points to the RIGHT. Exact grid 4 columns x 3 rows, each icon centered in its own equal cell with wide transparent gaps, all drawn at the same scale, each filling about 72% of its cell."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 4k --aspect_ratio 4:3 --background transparent --image-references $O/abilities_v2.png --image-references $O/upgrades_c_v2.png "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }
gen $O/hq_garage_v2.png --prompt "Sprite sheet of 12 game icons for headquarters technologies and vehicle upgrades. Row 1: 1 a field medical tent with a red cross; 2 two riveted armor panels with polished steel edges; 3 a polished robotic arm holding a wrench; 4 a supply crate with polished steel corners. Row 2: 5 an interceptor missile flying up-right with a flame trail; 6 a tesla coil with polished copper windings and small lightning; 7 a glowing ring pulse wave with a green cross in the middle; 8 a translucent blue protective dome. Row 3: 9 a dish antenna emitting waves; 10 a thick armor plate with polished bolts and bevelled edges; 11 a short polished cannon barrel with a muzzle flash to the right; 12 a coiled ammo belt with polished brass cartridges. $STYLE" &
gen $O/bonus_resources_v2.png --prompt "Sprite sheet of 12 game icons for field bonuses and resources. Row 1: 1 a big icy snowflake; 2 a big glossy gold star; 3 a small machine gun turret on a tripod facing right; 4 a small olive jeep facing right. Row 2: 5 a polished chrome wrench crossed over a rubber wheel; 6 a stack of red bricks; 7 a little concrete bunker with a polished wrench; 8 a rolled blue blueprint with a leather strap. Row 3: 9 a folder of documents with a red wax seal; 10 a recipe card with a small polished gear; 11 a polished gold trophy cup with a star; 12 a polished steel padlock. $STYLE" &
gen $O/stations_v2.png --prompt "Sprite sheet of 12 simple game icons for hub workbenches, each a single compact object, not a scene. Row 1: 1 a small 3D printer with a cat helmet inside; 2 a monitor showing a map; 3 a little car under a canopy roof, facing right; 4 a small bunker with an antenna. Row 2: 5 a red toolbox with a polished chrome wrench; 6 a market stall with a striped awning; 7 a round target board on sandbags; 8 a press machine with a polished gear. Row 3: 9 a cork board with pinned colored flags; 10 a locker with a hanging uniform; 11 a wooden rack with two rifles; 12 three orange traffic cones. $STYLE" &
wait
