#!/bin/zsh
# The HQ (штаб) is our mobile command vehicle, not a building (author, 2 Oct). Redraw every HQ picture as that vehicle.
cd "${0:A:h}/../.."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 4k --background transparent "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }
VEH="our mobile HQ: a chunky armored 4x4 command truck like the second reference image — sage-green and cream armored body, big rounded tires, a white satellite dish on the roof, short radio antennas, small red and yellow lights, a side door with a little window; facing RIGHT in three-quarter view"
STYLE="Same chunky toy-like 3D style as the first reference image. MATERIALS: polished shiny metal with soft rounded bevels, glossy low-roughness reflections (roughness about 0.2); rubber and canvas matte. Warm key light from upper-left. No text, no letters, no numbers, transparent background, no plates or frames behind the objects."
gen art_requests/icon_kit_v1/sheets/hq_vehicle_v2.png --aspect_ratio 3:2 --image-references art_requests/icon_kit_v1/sheets/hq_garage_v2.png --image-references art_requests/hq_health_icon_v1/mobile_hq_render.png --prompt "Sprite sheet of 6 game icons, exact grid 3 columns x 2 rows, each centered in its own equal cell with wide transparent gaps, same scale, each filling about 72% of its cell, unique readable silhouette at 32 pixels. All of them feature $VEH. 1 the command truck alone (headquarters category); 2 the command truck parked under a small open repair canopy with a polished wrench hanging (headquarters workbench in the hangar); 3 the command truck with a big polished chrome wrench and a bright repair spark in front of it (repair the HQ bonus); 4 a compact medical module box with a big red cross mounted on polished steel clamps, as fitted to the truck roof (medbay module); 5 the command truck with a small orange flag on its antenna, driving right (HQ milestone); 6 the command truck parked inside a hangar bay with a hydraulic lift and tools on the wall, a bit wider scene but still one compact object (HQ station picture). $STYLE" &
gen art_requests/icon_kit_v1/sheets/bp_hq_v2.png --aspect_ratio 1:1 --image-references art_requests/icon_kit_v1/sheets/blueprints_v2.png --image-references art_requests/hq_health_icon_v1/mobile_hq_render.png --prompt "One item in EXACTLY the same series as the first reference sheet: the same wooden clipboard with a polished steel clip, same angle, size and tilt, deep blue blueprint sheet with faint grid and a corner curl. The bold white technical line drawing on the sheet is a side view of an armored 4x4 command truck with a satellite dish on the roof and an antenna, facing RIGHT, like the second reference image. Single item centered, about 72% of the frame. No text, transparent background." &
wait
