#!/bin/zsh
# Stage 2 of the shiny-metal pass: run-card and stat symbols, 3 sheets x 15 (5 x 3). Style reference: abilities_v2.
cd "${0:A:h}/../.."
O=art_requests/icon_kit_v1/sheets
STYLE="Same chunky toy-like 3D style as the first reference image. One bold simple object per cell with a unique, instantly readable silhouette at 32 pixels; no plates, no frames, no circles or shapes behind, no background. MATERIALS: wherever there is metal, make it polished shiny metal with soft rounded bevels on every edge and glossy low-roughness reflections (roughness about 0.2), crisp soft specular highlights; painted parts are glossy enamel; fabric, wood and paper stay matte. Warm key light from upper-left. No text, no letters, no numbers, transparent background. Anything with a direction points to the RIGHT. Exact grid 5 columns x 3 rows, each icon centered in its own equal cell with wide transparent gaps, all drawn at the same scale, each filling about 72% of its cell."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 4k --aspect_ratio 16:9 --background transparent --image-references $O/abilities_v2.png --image-references $O/symbols_2_v1.png "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }

gen $O/upgrades_a_v2.png --prompt "Sprite sheet of 15 game upgrade icons, firepower. Row 1: 1 a big orange cartoon explosion burst; 2 a polished brass bullet with a bright burst at its tip, pointing right; 3 three polished brass bullets flying right in a row with speed lines; 4 a rifle magazine with speed lines; 5 a crosshair reticle with a yellow cat eye in the center. Row 2: 6 a polished brass bullet shattering into sharp shiny fragments, flying right; 7 a rifle scope with a small gold star; 8 a polished bullet hitting a small rocket mid-air with a spark, both flying right; 9 a bubble spirit level mounted on a short polished gun barrel; 10 an hourglass with a polished brass bullet beside it. Row 3: 11 a polished bullet piercing through three steel plates, flying right; 12 a torn red battle flag still standing on its pole; 13 a ringing polished brass bell with sound lines; 14 a tank hatch with a cat soldier in a helmet peeking out; 15 a polished steel grappling hook with rope. $STYLE" &

gen $O/upgrades_b_v2.png --prompt "Sprite sheet of 15 game upgrade icons, special ammo and survival. Row 1: 1 a single big orange flame; 2 a red thermometer standing inside a big orange flame; 3 a wooden torch with a long tall flame; 4 two flames linked by a crackling spark; 5 a bold yellow lightning bolt. Row 2: 6 a chunky battery with a lightning bolt, sparks overflowing; 7 a crackling electric arc between two tiny cars; 8 an electric plug with a short-circuit spark; 9 a spiral with three little stars (dizzy); 10 an olive cat helmet with stars and a big Z circling above it. Row 3: 11 a flash-bang grenade canister bursting with a white flash; 12 a big wooden mallet with polished steel bands and stars popping off; 13 a red heart held in an olive stylized ribcage; 14 a red first-aid kit with a polished steel clasp; 15 a heavy padded bomb-disposal helmet with a thick glossy visor. $STYLE" &

gen $O/upgrades_c_v2.png --prompt "Sprite sheet of 15 game upgrade icons, survival, recon and logistics. Row 1: 1 an olive bulletproof vest; 2 a tank shell ricocheting off a thick polished steel plate with a spark, flying right; 3 a curved wall of sandbags; 4 an army boot with a curved dodge arrow; 5 an army boot with wind streaks. Row 2: 6 a polished bullet with a long dotted arc trajectory to a small target, going right; 7 a camouflage hood cloak; 8 a dashed ghostly outline of a cat soldier; 9 a parachute carrying a supply crate; 10 an open car door with a dash arrow to the right. Row 3: 11 a four-leaf clover sticking out of a polished brass shell casing; 12 a bulging loot sack with coins; 13 a small polished steel safe with a dial; 14 an olive hand grenade with a circular clockwise arrow around it; 15 an olive hand grenade with a glowing upward arrow. $STYLE" &
wait
