const $=s=>document.querySelector(s), labels={graphics:'Графические',models:'3D-модели',audio:'Звук',other:'Все остальные'}, symbols={graphics:'▧',models:'◇',audio:'≋',other:'▤'};
let data=[],token='',tab='graphics',category='',reverse=false,selected=null,busy=false,toastTimer;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n<1024?n+' Б':n<1048576?(n/1024).toFixed(1)+' КБ':(n/1048576).toFixed(1)+' МБ';
const url=a=>'/file?path='+encodeURIComponent(a.path)+'&v='+a.modified;
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,9000)}
async function request(path,options={}){const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка запроса');return d}
async function refresh(manual=false){if(busy)return;busy=true;$('#refresh').disabled=true;try{const d=await request(manual||data.length?'/api/refresh':'/api/assets');const changed=JSON.stringify(d.assets)!==JSON.stringify(data);token=d.token;data=d.assets;if(changed||manual)render();$('#sync').textContent='Проверено '+new Date(d.scanned*1000).toLocaleTimeString('ru-RU')+' · авто: 15 сек';if(selected){const next=data.find(a=>a.path===selected.path);if(!next){$('#detail').close();selected=null;toast('Файл удалён из проекта')}else if(next.modified!==selected.modified){openDetail(next);toast('Предпросмотр обновлён: файл изменился')}}if(manual)toast('Данные обновлены')}catch(e){toast(e.message);$('#sync').textContent='Нет связи с локальной библиотекой'}finally{busy=false;$('#refresh').disabled=false}}
function visible(){const term=$('#search').value.toLowerCase();return data.filter(a=>a.kind===tab&&(tab!=='models'||$('#model-status').value==='all'||a.modelStatus===$('#model-status').value)&&(!category||a.category===category)&&($('#scope').value==='all'||a.scope===$('#scope').value)&&(!term||[a.name,a.path,...a.references.map(r=>r.file),...a.dynamic.map(r=>r.file)].join(' ').toLowerCase().includes(term))).sort((a,b)=>{const key=$('#sort').value;let n=['name','format'].includes(key)?a[key].localeCompare(b[key],'ru',{numeric:true}):key==='modified'?Number(BigInt(b.modified)-BigInt(a.modified)):b[key]-a[key];return (n||a.name.localeCompare(b.name,'ru',{numeric:true}))*(reverse?-1:1)})}
function render(){
 $('#model-status').hidden=tab!=='models';
 $('#tabs').innerHTML=Object.keys(labels).map(k=>`<button data-tab="${k}" class="${k===tab?'active':''}"><span>${symbols[k]} &nbsp;${labels[k]}</span><small>${data.filter(a=>a.kind===k).length}</small></button>`).join('');
 $('#tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;category='';render()});
 const categoryAssets=data.filter(a=>a.kind===tab&&(tab!=='models'||$('#model-status').value==='all'||a.modelStatus===$('#model-status').value));
 const cats=[...new Set(categoryAssets.map(a=>a.category))].sort();if(category&&!cats.includes(category))category='';
 $('#categories').innerHTML=`<button data-category="" class="${!category?'active':''}">Все категории</button>`+cats.map(c=>`<button data-category="${esc(c)}" title="${esc(c)}" class="${category===c?'active':''}"><span>${esc(c.replace(/^assets\//,''))}</span><small>${categoryAssets.filter(a=>a.category===c).length}</small></button>`).join('');
 $('#categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;render()});$('#title').textContent=labels[tab];
 const list=visible();$('#summary').innerHTML=`<div class="stat"><strong>${list.length}</strong><span>ассетов в выборке</span></div><div class="stat"><strong>${bytes(list.reduce((s,a)=>s+a.size,0))}</strong><span>общий размер</span></div><div class="stat"><strong>${list.filter(a=>a.scope==='game').length}</strong><span>в папке игровых ресурсов</span></div>`;
 $('#count').textContent=list.length+' файлов · '+new Set(list.map(a=>a.category)).size+' категорий';$('#empty').hidden=!!list.length;
 const groups=new Map();list.forEach(a=>{if(!groups.has(a.category))groups.set(a.category,[]);groups.get(a.category).push(a)});
 $('#grid').innerHTML=[...groups].map(([cat,items])=>`<section><h2 class="group-title">${esc(cat)} <small>${items.length}</small></h2><div class="cards">${items.map(a=>`<button class="card" data-path="${esc(a.path)}" title="${esc(a.path)}"><div class="thumb">${a.kind==='graphics'&&['PNG','JPG','JPEG','SVG','GIF','WEBP','BMP'].includes(a.format)?`<img loading="lazy" src="${esc(url(a))}" alt="${esc(a.name)}">`:`<span class="symbol">${symbols[a.kind]}</span>`}<span class="format">${esc(a.format)}</span></div><div class="card-body"><strong class="card-name">${esc(a.name)}</strong><div class="card-sub"><span>${bytes(a.size)}</span><span>${a.frequency} ссылок${a.dynamic.length?' · ≈':''}</span></div><span class="tag">${esc(a.importanceLabel)}</span></div></button>`).join('')}</div></section>`).join('');
 $('#grid').querySelectorAll('.card').forEach(b=>b.onclick=()=>openDetail(data.find(a=>a.path===b.dataset.path)));
}
function usageRows(rows){return rows.map(r=>`<div class="usage"><strong>${esc(r.file)}:${r.line}</strong><code>${esc(r.snippet)}</code></div>`).join('')}
async function openDetail(a){selected=a;$('#detail-name').textContent=a.name;$('#detail-kind').textContent=labels[a.kind]+' / '+a.format;$('#detail-path').textContent=a.path;$('#detail-meta').innerHTML=`<div class="metadata">${bytes(a.size)} · ${esc(a.importanceLabel)}<br>Изменён ${new Date(Number(BigInt(a.modified)/1000000n)).toLocaleString('ru-RU')}</div>`;
 $('#usage').innerHTML=(a.kind==='models'?`<p class="hint">${esc(a.importanceLabel)}${a.currentModel&&a.currentModel!==a.path?'<br>Загрузчик игры выбирает: <strong>'+esc(a.currentModel)+'</strong>':''}<br>Маршрут проверен по scripts/visuals.gd. Вид в игре может отличаться из-за масштаба, материалов и анимации.</p>`:'')+(a.references.length?`<div class="usage-heading">Найденные ссылки · ${a.frequency}</div>${usageRows(a.references)}`:'<p class="hint">Прямых ссылок не найдено. Это не доказывает, что ресурс не используется.</p>')+(a.dynamic.length?`<div class="usage-heading">Возможная динамическая загрузка · ${a.dynamic.length}</div><p class="hint">Код собирает путь из частей. Попадание конкретного файла требует проверки.</p>${usageRows(a.dynamic)}`:'');
 const p=$('#preview');p.replaceChildren();const src=url(a);
 if(a.kind==='graphics'&&['PNG','JPG','JPEG','SVG','GIF','WEBP','BMP'].includes(a.format)){const img=document.createElement('img');img.src=src;img.alt=a.name;p.append(img)}
 else if(a.format==='GLB'){const model=document.createElement('model-viewer');model.setAttribute('camera-controls','');model.setAttribute('auto-rotate','');model.setAttribute('shadow-intensity','1');model.setAttribute('environment-image','neutral');model.setAttribute('interaction-prompt','auto');model.setAttribute('alt',a.name);model.src=src;model.addEventListener('error',()=>{p.innerHTML='<p class="preview-message">Не удалось открыть модель. Проверьте файл через «Открыть путь».</p>'});p.append(model)}
 else if(a.kind==='audio'){p.innerHTML='<span class="symbol">≋</span>';const audio=document.createElement('audio');audio.controls=true;audio.src=src;p.append(audio)}
 else if(['MP4','WEBM'].includes(a.format)){const v=document.createElement('video');v.controls=true;v.src=src;p.append(v)}
 else if(a.format==='PDF'){const f=document.createElement('iframe');f.title=a.name;f.src=src;p.append(f)}
 else if(['JSON','TXT','MD','CSV','TRES','GDSHADER'].includes(a.format)&&a.size<2_000_000){const pre=document.createElement('pre');pre.textContent='Загрузка…';p.append(pre);fetch(src).then(r=>{if(!r.ok)throw Error('Не удалось прочитать файл');return r.text()}).then(t=>pre.textContent=t).catch(e=>pre.textContent=e.message)}
 else {p.innerHTML=`<span class="symbol">${symbols[a.kind]}</span><p class="preview-message">${a.format==='BLEND'?'Исходник Blender. Откройте папку файла, чтобы редактировать его в Blender.':'Для этого формата предпросмотр в браузере недоступен.'}<br>Для интерактивного 3D-просмотра используйте GLB.</p>`}
 if(!$('#detail').open)$('#detail').showModal();
}
$('#close').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>{$('#preview').replaceChildren();selected=null});
$('#fullscreen').onclick=async()=>{try{await $('#preview').requestFullscreen()}catch(e){toast('Полноэкранный режим недоступен в этом браузере')}};
$('#reveal').onclick=async()=>{try{await request('/api/reveal?path='+encodeURIComponent(selected.path),{method:'POST',headers:{'X-Asset-Token':token}})}catch(e){toast(e.message)}};
$('#replace').onclick=()=>{$('#upload').accept='.'+selected.format.toLowerCase();$('#upload').value='';$('#upload').click()};
$('#upload').onchange=async()=>{const file=$('#upload').files[0],a=selected;if(!file||!a)return;if(file.name.split('.').pop().toLowerCase()!==a.format.toLowerCase())return toast('Выберите файл того же формата: '+a.format);if(!confirm(`Заменить ${a.path} содержимым ${file.name}?\nИмя и путь сохранятся. Предыдущая версия будет сохранена в резервной копии.`))return;$('#replace').disabled=true;try{const result=await request('/api/replace?path='+encodeURIComponent(a.path),{method:'POST',headers:{'X-Asset-Token':token,'X-Filename':encodeURIComponent(file.name),'X-Modified':a.modified},body:file});await refresh();toast('Файл заменён. Резервная копия: '+result.backup)}catch(e){toast(e.message)}finally{$('#replace').disabled=false}};
$('#refresh').onclick=()=>refresh(true);$('#search').oninput=render;$('#scope').onchange=render;$('#model-status').onchange=()=>{category='';render()};$('#sort').onchange=()=>{reverse=false;$('#direction').textContent='↓';render()};$('#direction').onclick=()=>{reverse=!reverse;$('#direction').textContent=reverse?'↑':'↓';render()};
refresh();setInterval(()=>{if(!document.hidden&&!$('#replace').disabled)refresh()},15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
