#!/bin/zsh
# Route map points redesign, concept sheets 2x2 at 2048x2048 (author, 2 Oct). Every node type the route plan can make.
cd "${0:A:h}/../.."
O=art_requests/route_points_v1
R=art_requests/reference_shots_v1/06_route_map.png
STYLE="Concept sheet, exact grid 2 columns x 2 rows, four equal square cells with a thin gap, each cell one route-map point: a small round low-poly diorama tile (same footprint and size in every cell, about 70% of the cell) seen from the same high three-quarter top-down camera as the route map in the reference image, on a plain soft neutral background. The game's simple minimalist style: chunky low-poly shapes, soft pastel palette with sage green, cream and soft orange accents, flat clean materials, soft daylight from upper-left, gentle shadows; small metal parts (barrels, guns, rails, signs) polished with soft bevels and gentle reflections (roughness about 0.2). Readable at a small size: one clear focal object per tile, few props. No characters in focus, no text, no letters, no numbers."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 2k --aspect_ratio 1:1 --image-references $R "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }
gen $O/battles_a.png --prompt "Battle points by difficulty, each on a different biome tile. Top-left EASY battle on a green FOREST tile: a small outpost — a ring of sandbags, one machine-gun nest, a couple of round trees. Top-right MEDIUM battle on a sandy DESERT tile: an enemy supply depot — stacked crates and fuel barrels behind a low wall, a small watchtower. Bottom-left HARD battle on a snowy FROST tile: a concrete fire base — a bunker with a gun slit, a sweeping searchlight, barbed wire. Bottom-right BOSS on a scorched ASH tile: the general's lair — a dark plated platform ringed with spikes, a big boss tank in the middle, two fire braziers and red beacons. Difficulty grows visibly from top-left to bottom-right. $STYLE" &
gen $O/battles_b.png --prompt "Challenge points, each on a different biome tile. Top-left CACHE challenge on a COAST tile (sand and water): a supply cache — a big locked steel crate with a glowing lid half-buried by the shore, a few sandbags, ambush hiding spots. Top-right HOLD challenge on a CITY tile: a flag on a pole in a small courtyard of ruined walls, a sandbag ring around it, defend the flag. Bottom-left SURVIVE challenge on a MARSH tile: a lone trench island in a swamp with reeds, a stopwatch-shaped beacon lamp, enemies' paths converging. Bottom-right DARK MAZE challenge on a night STEPPE tile: a dark hedge-and-wall labyrinth seen from above with a tiny green flag glowing at its exit and a lantern at the entrance. $STYLE" &
gen $O/services.png --prompt "Service (upgrade) stops between battles, on neutral packed-earth tiles. Top-left TRAINING POINT (abilities instructor): a little drill ground with a chalkboard, a training dummy and a grenade crate. Top-right MERCHANT: a small market stall with a striped orange-cream awning, crates of goods and a lantern. Bottom-left VEHICLE HANGAR (mechanic): an open hangar bay with a lift, a buggy on it, a tool wall and a fuel pump. Bottom-right HQ WORKSHOP pit stop: an open bay with chevrons leading in where the armored 4x4 command truck with a satellite dish gets serviced, a crane arm and a crate of parts. $STYLE" &
gen $O/specials.png --prompt "Special points. Top-left CAPTURED COMMAND POST (legendary reward): a dark enemy bunker with a torn red flag, sandbags, a radio mast and a glowing golden chest at the door. Top-right START pad: a round concrete platform with a launch gate and chevrons where the command truck leaves from. Bottom-left an alternative EASY battle on a STEPPE tile: a road checkpoint with a barrier arm and a small booth. Bottom-right an alternative MEDIUM battle on an URBAN tile: a convoy of two trucks under a camouflage net between ruined walls. $STYLE" &
wait
