#!/bin/zsh
# Inventory items in a strict side view (author, 3 Oct): weapons, ammo (big round in front, small box behind with a
# coloured effect stripe), blueprints (calmer, strict, rarity chevron drawn separately).
cd "${0:A:h}/../.."
O=art_requests/inventory_side_v1
R=art_requests/icon_kit_v1/sheets
STYLE="Same chunky toy-like 3D style as the reference, polished metal with soft rounded bevels (roughness about 0.2), matte wood, paper and cardboard, warm soft light from upper-left. STRICT ORTHOGRAPHIC SIDE VIEW for every item: camera exactly level, no three-quarter angle, no perspective, no tilt; items rest on an invisible common baseline. Every item centered in its own equal cell with wide transparent gaps, nothing touching. No text, no letters, no numbers, transparent background."
gen(){ local out=$1; shift
  local url=$(higgsfield generate create gpt_image_2_5 --quality high --resolution 4k --background transparent "$@" --wait --wait-timeout 20m 2>&1 | grep -Eo 'https://[^ ]+\.png' | tail -1)
  [ -z "$url" ] && { echo "FAILED $out"; return 1; }
  curl -sSL -o "$out" "$url" && echo "OK $out"; }
gen $O/weapons.png --aspect_ratio 16:9 --image-references assets/illustrations/gpt_image_2_5/icons/weapons/rifle.png --image-references assets/illustrations/gpt_image_2_5/icons/weapons/pistol.png --prompt "Sprite sheet of 8 game weapons for an inventory, exact grid 4 columns x 2 rows, each weapon filling the width of its cell, all at the same scale relative to each other but each enlarged to fill its cell width, MUZZLE POINTING RIGHT. Row 1: 1 compact pistol, dark metal slide, olive grip, small orange dot; 2 pump-action shotgun with wooden forend and stock; 3 short submachine gun with straight magazine and folding stock; 4 assault rifle with curved magazine and wooden stock. Row 2: 5 long sniper rifle with a big scope, folded bipod; 6 RPG launcher tube with an olive warhead with an orange band at the right end; 7 belt-fed light machine gun with an ammo belt and bipod; 8 revolver grenade launcher with a fat drum and short wide barrel. $STYLE" &
gen $O/ammo.png --aspect_ratio 16:9 --image-references $R/ammo_v2.png --prompt "Sprite sheet of 10 ammunition inventory items in ONE consistent series, exact grid 5 columns x 2 rows. EVERY cell has EXACTLY the same composition in strict side view: ONE big upright cartridge standing in front, slightly left of centre, filling most of the cell height; behind it, to the right and lower, a SMALL closed ammo box (about half the cartridge height) with ONE coloured stripe across the box marking the effect. The cartridge tip/material also shows the effect subtly. Row 1: 1 STANDARD: brass cartridge, copper tip, plain olive box with a cream stripe; 2 INCENDIARY: orange stripe, glowing red-orange tip; 3 STUN: yellow stripe, yellow banded tip; 4 EMP: cyan stripe, electric blue tip; 5 EXPLOSIVE: red stripe, red tip with hot seam. Row 2: 6 ARMOR-PIERCING: silver-grey stripe, sharp polished steel penetrator tip; 7 RICOCHET: violet stripe, violet tip; 8 CRYO: icy light-blue stripe, frosty crystal tip; 9 CLUSTER: golden-yellow stripe, a fat 40mm grenade round with a segmented golden nose instead of a rifle cartridge; 10 NAPALM: deep orange stripe, a fat 40mm grenade round with a glowing deep-orange nose. $STYLE" &
gen $O/blueprints.png --aspect_ratio 16:9 --image-references $R/blueprints_v2.png --prompt "Sprite sheet for blueprint inventory items, exact grid 5 columns x 2 rows. Row 1 and the first cell of row 2: six blueprint items, calm and strict, less flashy than the reference: a flat rectangular deep navy-blue blueprint sheet seen straight on (no clipboard, no curl), thin pale grid, a thin cream border, a small polished steel clip at the top edge; in the middle ONE clean white line-drawing silhouette: 1 an assault rifle side view pointing right; 2 a tank side view facing right; 3 an armored 4x4 command truck with a satellite dish, facing right; 4 a hand grenade; 5 a supply crate with a star; 6 a small workshop building with a gear. Then cells 7-10: four separate small military rank chevron patches (cloth patch with embroidered stripes, flat front view) for rarity: 7 one grey chevron; 8 two blue chevrons; 9 three violet chevrons; 10 three gold chevrons with a small star. $STYLE" &
wait
